### ISSUE TITLE
Use a git submodule for speexdsp

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/Dependencies#10]
libspeex should be updated to [speexdsp](https://github.com/xiph/speexdsp).

Remove libspeex sources, away from the shared project and use a submodule for the latest stable release of speexdsp instead.

**Comment by janisozaur** [comment]
See also https://github.com/OpenRCT2/OpenRCT2/issues/3229

**Comment by LRFLEW** [comment]
Fixed as part of #11
